import React from 'react';
import type { CharacterVoice } from './utils/speech';

/**
 * Story content only (no UI). Every conversation covers four ideas, in kid words:
 *   PURPOSE  - why it was sent
 *   HARDWARE - what it was made of / carried
 *   SCIENCE  - what we learned because of it
 *   STATUS   - where it is now and whether it still talks to Earth
 * {{key|text}} marks a word that opens a glossary pop-up (see SPACE_GLOSSARY).
 * Facts come from the NSSDCA pages / project GeoJSON; see notes in the hand-off message.
 */

export type Line = [string, string];

/** Expand [question, answer] pairs into the Orbit <-> spacecraft chat format. */
export const chat = (who: string, pairs: [string, string][], closer?: string): Line[] => {
  const out: Line[] = [];
  pairs.forEach(([q, a]) => {
    out.push(['Orbit', q]);
    out.push([who, a]);
  });
  if (closer) out.push(['Orbit', closer]);
  return out;
};

interface BeatInput {
  id: string;
  name: string; // chat speaker name (must match SPEAKERS in InterviewChat)
  voice?: CharacterVoice;
  lead: string; // short speech-bubble quote
  body: string; // one-paragraph kid summary
  speech: string; // spoken line for the illustration
  fact: string; // "NASA Discovery" box
  interview: Line[];
  emoji: string;
  year: string;
  orbitLine: string;
}

const mk = (b: BeatInput) => ({
  id: b.id,
  pageNumber: 0,
  layout: 'both_generic' as const,
  speaker: (b.voice ?? 'narrator') as CharacterVoice,
  speakerName: `${b.name} & Orbit`,
  isConversation: true,
  orangeVariant: 'meridiani' as const,
  leadQuote: b.lead,
  bodyComponent: <span>{b.body}</span>,
  speechText: b.speech,
  scienceFact: b.fact,
  interview: b.interview,
  art: { emoji: b.emoji, name: b.name, year: b.year },
  orbitLine: b.orbitLine,
});

/* ------------------------------------------------------------------ */
/*  REWRITTEN INTERVIEWS FOR THE EXISTING CHARACTERS (applied by id)   */
/* ------------------------------------------------------------------ */
export const REWRITTEN: Record<string, Line[]> = {
  'mars-viking-1': chat('Viking 1', [
    ['Viking 1, why did you go to Mars?', 'To land safely, take pictures, and test the soil for signs of life!'],
    ['What were you built with?', 'Two cameras, a robot arm that scooped up soil, and a weather mast.'],
    ['Anything else?', 'A {{seismometer|quake sensor}} and a tiny biology lab in a box!'],
    ['Did you find life?', 'My tests gave puzzling answers, so no clear proof. But I measured Mars weather and soil.'],
    ['How long did you work?', 'I landed in 1976 and kept sending data until November 1982.'],
    ['Where are you now?', 'Switched off, right where I landed. No signal since 1982.'],
  ]),
  'mars-sojourner': chat('Sojourner', [
    ['Sojourner, what was your job?', 'Roll off my lander and study Martian rocks and soil up close!'],
    ['What are you like?', 'A small six-wheeled rover, about as big as a microwave oven.'],
    ['How did you check rocks?', 'I touched them with a {{spectrometer|rock-chemistry sensor}} that tells what a rock is made of.'],
    ['How long were you supposed to work?', 'Just 7 Mars days… but I explored for 83!'],
    ['What did we learn from you?', 'That small, low-cost rovers can explore Mars. I also sent back rock and weather data.'],
    ['Where are you now?', 'Resting near my {{pathfinder|Pathfinder}} home. My last signal came on 27 September 1997.'],
  ], 'Mission complete, little rover.'),
  'mars-spirit': chat('Spirit', [
    ['Spirit, what were you looking for on Mars?', 'Rocks and clues that water once existed there!'],
    ['What were you built with?', 'Six wheels, solar panels, cameras, and a robot arm.'],
    ['What could the arm do?', 'It could scrape rock and use a {{spectrometer|rock-chemistry sensor}} to read what was inside.'],
    ['Did you find anything?', 'Yes! In Gusev Crater I found proof that ancient water changed the rocks.'],
    ['How long were you supposed to explore?', 'Just 90 Martian days… but I worked for over 6 years and drove 7.7 km!'],
    ['What stopped you?', 'I got stuck in soft sand in 2009. My last call to Earth was 22 March 2010.'],
    ['And now?', 'I am still resting on Mars, with my discoveries.'],
  ]),
  'mars-opportunity': chat('Oppy', [
    ['Oppy, why did you go to Mars?', 'To find out if Mars once had water, at a place called Meridiani Planum.'],
    ['What did you find?', 'Tiny round {{blueberries|blueberries}}, made in water!'],
    ['What does that tell us?', 'Together, Spirit and I showed that water stayed on Mars for a long time.'],
    ['What were you built with?', 'Solar panels, cameras, a robot arm, and tools to study rocks.'],
    ['How long were you supposed to explore?', 'Only 90 sols. I made it 5,111 and drove 45 km!'],
    ['What stopped you?', 'A huge dust storm covered my solar panels. My last message came on 10 June 2018.'],
  ], "You're still on Mars, Oppy, in Perseverance Valley."),
  'moon-surveyor-1': chat('Surveyor 1', [
    ['Surveyor 1, what was your mission?', 'Land softly on the Moon and check what the ground was really like! 🌕'],
    ['What were you built like?', 'A three-legged lander with a TV camera and a {{retrorocket|braking rocket}} to slow my fall.'],
    ['What did you send back?', 'More than 11,000 pictures and measurements of how strong the ground is.'],
    ['Why did that matter?', 'It showed the Moon could hold up a spacecraft. That was a big step toward Apollo.'],
    ['Were you the first?', 'Yes, the first U.S. soft landing on the Moon!'],
    ['Where are you now?', 'In the Ocean of Storms. My pictures ended in July 1966 and my last contact was January 1967.'],
  ]),
  'moon-grail-a': chat('GRAIL-A (Ebb)', [
    ['Ebb, why did you and Flow go to the Moon?', 'To map the Moon’s gravity!'],
    ['How does a spacecraft measure gravity?', 'We flew in a line and tracked our distance with radio signals.'],
    ['Why does that work?', 'Heavier ground tugs us. We speed up and slow down by tiny amounts.'],
    ['What did you learn?', 'The Moon’s outer crust is thin and battered, with hidden features underneath.'],
    ['How did your mission end?', 'On 17 December 2012, we were steered on purpose into a mountain near the north pole.'],
    ['So where are you now?', 'Still on the Moon, and no longer sending signals.'],
  ], 'You and Flow really went out together.'),
  'moon-grail-b': chat('GRAIL-B (Flow)', [
    ['Flow, what was your job?', 'Fly beside Ebb and help map the Moon’s gravity.'],
    ['Who named you two?', 'School students in Montana picked Ebb and Flow, like ocean tides.'],
    ['What are you built like?', 'Each of us is about the size of a washing machine.'],
    ['What was inside?', 'Radio gear that measured how far apart we were.'],
    ['Did you make a good team?', 'The perfect pair! We made the most detailed gravity map of any world.'],
    ['And your final journey?', 'We crashed together near the north pole in December 2012. We are still there.'],
  ], 'Mission complete, together.'),
  'moon-apollo-11': chat('Apollo 11', [
    ['Apollo 11, why did you go to the Moon?', 'To land people on the Moon and bring them safely home!'],
    ['What hardware stayed behind?', 'The bottom half of our lunar module, called the descent stage.'],
    ['Why was it left?', 'It was the launch pad for the top half, which carried the crew home.'],
    ['What science did you leave?', 'A {{seismometer|quake sensor}}, a dust detector, and a mirror for bouncing lasers.'],
    ['What did you bring back?', 'About 21.5 kg of Moon rocks and soil to study on Earth.'],
    ['Where are you now?', 'At Tranquility Base. The descent stage stopped working in 1969, but it is still there.'],
  ], 'First footprints, forever remembered.'),
  'moon-apollo-15': chat('Apollo 15', [
    ['Apollo 15, what made your trip special?', 'We were the first crew to drive a Lunar Roving Vehicle!'],
    ['A car on the Moon?!', 'It folded up inside our lander. On Earth it weighed only 210 kg.'],
    ['What powered it?', 'Two big batteries and four electric motors.'],
    ['What did it let you do?', 'We drove 27.8 km and gathered 77 kg of rocks.'],
    ['What else did you leave?', 'The lander’s bottom half and a science station called ALSEP.'],
    ['Where is your rover now?', 'Parked at Hadley-Apennine since 1971, and no longer working.'],
  ], 'Moon parking!'),
  'deep-pioneer-5': chat('Pioneer 5', [
    ['Pioneer 5, where were you headed?', 'Into space to study the Sun and the space between Earth and Venus!'],
    ['What are you like?', 'A round, spinning probe covered in solar cells.'],
    ['What did you carry?', 'Sensors for magnetic fields and {{solar_particles|solar particles}}.'],
    ['What did you discover?', 'How the Sun’s particles and magnetism fill space.'],
    ['Why did you stop talking?', 'My signal grew too weak. My last contact was in 1960.'],
    ['Where are you now?', 'Still going around the Sun.'],
  ], 'Still circling the Sun after all these years!'),
  'deep-mariner-2': chat('Mariner 2', [
    ['Mariner 2, where were you going?', 'To Venus!'],
    ['Did you make it?', 'Yes! In December 1962 I was the first spacecraft to visit another planet.'],
    ['What were you built with?', 'Solar panels, a dish antenna, and {{radiometer|heat sensors}}.'],
    ['What did you discover?', 'Venus is scorching hot.'],
    ['Anything else?', 'I also measured the wind blowing out from the Sun.'],
    ['Where are you now?', 'Going around the Sun. My contact ended in January 1963.'],
  ]),
  'deep-mariner-10': chat('Mariner 10', [
    ['Mariner 10, why were you sent out?', 'To visit Mercury!'],
    ['How did you get there?', 'I used Venus’s {{gravity_assist|gravity boost}}. I was the first to try it.'],
    ['What did you carry?', 'Cameras and a {{magnetometer|magnet sensor}}.'],
    ['What did you discover?', 'Mercury has a magnetic field, and its face is covered in craters.'],
    ['How many times did you visit?', 'Three flybys of Mercury!'],
    ['Where are you now?', 'Going around the Sun. I went silent on 24 March 1975, when my steering gas ran out.'],
  ], 'Your Mercury adventure lives on!'),
  'deep-pioneer-10': chat('Pioneer 10', [
    ['Pioneer 10, where were you headed?', 'Jupiter! I was the first to cross the {{asteroid_belt|asteroid belt}} and visit the giant planet.'],
    ['What are you built with?', 'A big dish antenna and a {{rtg|nuclear battery}} for power.'],
    ['Do you carry anything special?', 'A golden plaque with a message, in case anyone finds me.'],
    ['What did you learn?', 'Jupiter has dangerous radiation. That helped design later spacecraft.'],
    ['Did you keep going?', 'Yes, outward toward the stars.'],
    ['Why did you stop talking?', 'My last signal reached Earth on 23 January 2003. My power was too weak.'],
  ], 'Still traveling… just very, very quietly.'),
  'deep-pioneer-11': chat('Pioneer 11', [
    ['Pioneer 11, what was your big adventure?', 'First Jupiter, then Saturn! I was the first to fly past Saturn.'],
    ['What are you built with?', 'Cameras, a {{magnetometer|magnet sensor}}, and a {{rtg|nuclear battery}}.'],
    ['What did you discover?', 'Close-up views of Saturn and its rings.'],
    ['Anything new?', 'I spotted another ring around Saturn!'],
    ['Where are you now?', 'Still moving away from the Sun.'],
    ['Why did you stop talking?', 'My last contact with Earth was in 1995.'],
  ], 'Another pioneer heading into the dark.'),
  'deep-voyager-1': chat('Voyager 1', [
    ['Voyager 1, where were you supposed to go?', 'Jupiter and Saturn!'],
    ['And then?', 'I just… kept going.'],
    ['What keeps you alive?', 'A {{rtg|nuclear battery}}, a big dish antenna, and sensors for magnetism and particles.'],
    ['Do you carry anything special?', 'A Golden Record with sounds and pictures from Earth.'],
    ['What did you discover?', 'Close views of Jupiter and Saturn. In 2012 I entered {{interstellar|interstellar space}}.'],
    ['Are you still talking to Earth?', 'Yes! I send a little science and engineering data from my aging systems.'],
  ], 'The little traveler that just won’t stop'),
};

/* ------------------------------------------------------------------ */
/*  MARS (adds Viking 2, orbiters, flybys, lost missions, landers)     */
/* ------------------------------------------------------------------ */
export const MARS_EXTRA = [
  mk({
    id: 'mars-viking-2', name: 'Viking 2', voice: 'viking1', emoji: '🔭', year: '1976',
    lead: 'I looked at frost on Mars!',
    body: 'Viking 2 landed on the northern plains of Mars in 1976 to study the soil, air and weather. It worked until April 1980.',
    speech: 'I landed on the northern plains of Mars in 1976 and kept working until 1980!',
    fact: 'Viking 2 landed in Utopia Planitia and worked until 11 April 1980, when its batteries failed.',
    orbitLine: 'Viking 2, what did you see on Mars?',
    interview: chat('Viking 2', [
      ['Viking 2, why did you go to Mars?', 'To study the soil, air, weather and ground of Mars.'],
      ['What were you built with?', 'Two cameras, a robot sampler arm, and a weather mast.'],
      ['Anything else?', 'A {{seismometer|quake sensor}} and a tiny biology lab.'],
      ['What did you discover?', 'Sunrise pictures, Mars weather, and soil chemistry.'],
      ['Anything surprising?', 'My cameras saw a thin layer of frost on the ground!'],
      ['What ended your mission?', 'My batteries failed, and I was shut off on 11 April 1980.'],
      ['Where are you now?', 'Still on Mars, where I landed. My full name is the Gerald Soffen Memorial Station.'],
    ]),
  }),
  mk({
    id: 'mars-viking-1-orbiter', name: 'Viking 1 Orbiter', voice: 'viking1', emoji: '🛰️', year: '1975',
    lead: 'I took the pictures from above!',
    body: 'The Viking 1 Orbiter circled Mars, photographed the planet, and passed messages for its lander. It worked until August 1980.',
    speech: 'I circled Mars, mapped it from above, and passed messages for my lander!',
    fact: 'The Viking orbiters photographed most of Mars from space, helping pick landing sites.',
    orbitLine: 'Viking 1 Orbiter, what did you do up there?',
    interview: chat('Viking 1 Orbiter', [
      ['Viking 1 Orbiter, what was your job?', 'Circle Mars, take pictures, and pass messages for my lander.'],
      ['What were you built with?', 'Cameras, and two sensors for heat and water vapor.'],
      ['What did you discover?', 'Giant volcanoes and deep canyons.'],
      ['Anything about water?', 'Channels that look carved by flowing water long ago!'],
      ['How did your mission end?', 'My steering gas was almost gone. Contact ended on 17 August 1980.'],
      ['Where are you now?', 'Still going around Mars, silent.'],
    ]),
  }),
  mk({
    id: 'mars-viking-2-orbiter', name: 'Viking 2 Orbiter', voice: 'viking1', emoji: '🛰️', year: '1975',
    lead: 'A gas leak ended my mission.',
    body: 'The Viking 2 Orbiter mapped Mars from above for about two years before a gas leak ended its mission in 1978.',
    speech: 'I mapped Mars from above until a gas leak ended my mission in 1978.',
    fact: 'The Viking 2 Orbiter was shut down in July 1978 after a leak drained its steering gas.',
    orbitLine: 'Viking 2 Orbiter, what happened to you?',
    interview: chat('Viking 2 Orbiter', [
      ['Viking 2 Orbiter, why did you go to Mars?', 'To photograph Mars from above and pass messages for my lander.'],
      ['What were you built with?', 'Twin cameras and two sensors for heat and water vapor.'],
      ['What did you find?', 'Thousands of pictures of channels and volcanoes.'],
      ['Did you look at anything else?', 'Yes! I studied Mars’s two small moons.'],
      ['What ended your mission?', 'A leak drained my steering gas. I was shut off in July 1978.'],
      ['Where are you now?', 'Still going around Mars, out of contact.'],
    ]),
  }),
  mk({
    id: 'mars-mariner-4', name: 'Mariner 4', voice: 'mariner2', emoji: '📸', year: '1964',
    lead: 'I took the first close-ups of Mars!',
    body: 'Mariner 4 flew past Mars in July 1965 and took the first close-up pictures of another planet.',
    speech: 'I flew past Mars in 1965 and took the first close-up pictures of the planet!',
    fact: 'Mariner 4 showed Mars is covered in craters and has very thin air. Its last contact was 21 December 1967.',
    orbitLine: 'Mariner 4, what did Mars look like?',
    interview: chat('Mariner 4', [
      ['Mariner 4, what was your mission?', 'Zoom past Mars and take the first close-up pictures.'],
      ['What were you built with?', 'A TV camera and solar panels.'],
      ['What else did you carry?', 'Sensors for space dust, particles, and Mars’s thin {{atmosphere|air}}.'],
      ['What did you discover?', 'Mars has craters, like the Moon!'],
      ['What about the air?', 'It is very thin, much thinner than Earth’s.'],
      ['How long did you work?', 'Until 21 December 1967.'],
      ['Where are you now?', 'Going around the Sun, in silence.'],
    ]),
  }),
  mk({
    id: 'mars-mariner-6', name: 'Mariner 6', voice: 'mariner2', emoji: '📸', year: '1969',
    lead: 'Two flybys, double the pictures!',
    body: 'Mariner 6 flew past Mars in 1969 with its twin, Mariner 7, to photograph it and study its air.',
    speech: 'My twin and I flew past Mars in 1969 and studied its air and surface!',
    fact: 'Mariners 6 and 7 found that Mars’s air is mostly carbon dioxide and sent about 200 pictures.',
    orbitLine: 'Mariner 6, tell us about your Mars flyby!',
    interview: chat('Mariner 6', [
      ['Mariner 6, what was your job?', 'Zoom past Mars, take pictures, and study its air and ground.'],
      ['What were you built with?', 'Two TV cameras, plus sensors for heat and light.'],
      ['What did you find?', 'Mars’s air is mostly carbon dioxide.'],
      ['What did you see?', 'Craters and bright polar caps.'],
      ['Are you still talking?', 'No. NASA’s records don’t say exactly when I went quiet.'],
      ['Where are you now?', 'Going around the Sun.'],
    ]),
  }),
  mk({
    id: 'mars-mariner-7', name: 'Mariner 7', voice: 'mariner2', emoji: '📸', year: '1969',
    lead: 'I came in over the south pole!',
    body: 'Mariner 7 flew past Mars days after Mariner 6 and sent back even more pictures.',
    speech: 'I flew past Mars days after my twin and sent back even more pictures!',
    fact: 'Mariner 7 flew over Mars’s south pole. Its data showed the polar cap is mostly frozen carbon dioxide.',
    orbitLine: 'Mariner 7, what did you see?',
    interview: chat('Mariner 7', [
      ['Mariner 7, why did you go to Mars?', 'To study its surface and air, together with Mariner 6.'],
      ['What were you built with?', 'The same as my twin: cameras and sensors for heat and light.'],
      ['What did you discover?', 'The south polar cap looks like frozen carbon dioxide, or dry ice.'],
      ['Did you take pictures?', 'Yes, even more than my twin, about 126 in all.'],
      ['Are you still talking?', 'No. NASA’s records don’t say exactly when I went quiet.'],
      ['Where are you now?', 'Going around the Sun.'],
    ]),
  }),
  mk({
    id: 'mars-observer', name: 'Mars Observer', voice: 'narrator', emoji: '📡', year: '1992',
    lead: 'I vanished three days early.',
    body: 'Mars Observer was the first U.S. mission to Mars in 18 years. Contact was lost on 21 August 1993, three days before it arrived.',
    speech: 'I was three days from Mars when contact was lost in 1993.',
    fact: 'Investigators think a leak mixed rocket fuel and a chemical that burns it, and that damaged Mars Observer’s fuel pipes.',
    orbitLine: 'Mars Observer, what went wrong?',
    interview: chat('Mars Observer', [
      ['Mars Observer, why were you sent?', 'To circle Mars and study its ground, air and magnetism.'],
      ['What were you built with?', 'A camera, a {{altimeter|laser height-meter}}, and sensors for rock chemistry and heat.'],
      ['What happened?', 'Contact stopped on 21 August 1993, just three days before I reached Mars.'],
      ['Why did it happen?', 'Investigators think my fuel pipes broke while my fuel tanks were being filled with gas.'],
      ['Did you send any science?', 'No, I never reached Mars orbit.'],
      ['Did anything good come of it?', 'Yes. Some of my instruments were rebuilt and flew on later missions.'],
      ['Where are you now?', 'Unknown. No signal has been heard since.'],
    ]),
  }),
  mk({
    id: 'mars-global-surveyor', name: 'Mars Global Surveyor', voice: 'narrator', emoji: '🛰️', year: '1996',
    lead: 'I mapped Mars for nine years!',
    body: 'Mars Global Surveyor circled Mars from 1997 until it went quiet on 2 November 2006.',
    speech: 'I mapped Mars from orbit for nine years, until I went silent in 2006.',
    fact: 'Mars Global Surveyor found gullies, layered rocks, and magnetic stripes in the crust of Mars.',
    orbitLine: 'Mars Global Surveyor, what did you map?',
    interview: chat('Mars Global Surveyor', [
      ['Mars Global Surveyor, what was your job?', 'Circle Mars and map its surface, air and magnetism.'],
      ['What were you built with?', 'A sharp camera, a {{altimeter|laser height-meter}}, and a {{magnetometer|magnet sensor}}.'],
      ['What did you discover?', 'Layered rocks and gullies that may have been cut by flowing liquid.'],
      ['Anything about magnetism?', 'Stripes of old magnetism hiding in the ground!'],
      ['How did your mission end?', 'I lost contact on 2 November 2006.'],
      ['Where are you now?', 'Still going around Mars, silent.'],
    ]),
  }),
  mk({
    id: 'mars-climate-orbiter', name: 'Mars Climate Orbiter', voice: 'narrator', emoji: '📏', year: '1998',
    lead: 'A units mix-up sent me too low.',
    body: 'Mars Climate Orbiter reached Mars on 23 September 1999 but flew far too low. Some engineers had used English units while others used metric.',
    speech: 'A units mix-up sent me too close to Mars in 1999.',
    fact: 'Mars Climate Orbiter passed at about 57 km above Mars instead of the planned 140–150 km, because of a pounds versus newtons mix-up.',
    orbitLine: 'Mars Climate Orbiter, what went wrong?',
    interview: chat('Mars Climate Orbiter', [
      ['Mars Climate Orbiter, what was your mission?', 'Study Mars’s weather and climate, and pass messages for landers.'],
      ['What were you built with?', 'A weather camera, a {{radiometer|heat sensor}}, and a big solar panel.'],
      ['What went wrong?', 'Some engineers used English units, and others used metric units.'],
      ['What did that cause?', 'I flew about 57 km above Mars instead of 140. That was too low!'],
      ['What happened next?', 'The thick air probably destroyed me. Contact was lost on 23 September 1999.'],
      ['Did you send science?', 'No. But I taught everyone to double-check their units.'],
      ['Where are you now?', 'Lost: I either burned up or flew past Mars.'],
    ], 'A tiny units mix-up, a huge lesson.'),
  }),
  mk({
    id: 'mars-polar-lander', name: 'Mars Polar Lander', voice: 'narrator', emoji: '🪂', year: '1999',
    lead: 'I never called home.',
    body: 'Mars Polar Lander was meant to land near Mars’s south pole in December 1999. It never called Earth after landing.',
    speech: 'I was supposed to land near Mars’s south pole, but I never called home.',
    fact: 'The last signal from Mars Polar Lander came just before it entered Mars’s air on 3 December 1999. No one knows what went wrong.',
    orbitLine: 'Mars Polar Lander, what happened at the pole?',
    interview: chat('Mars Polar Lander', [
      ['Mars Polar Lander, why did you go to Mars?', 'To study weather, ice and soil near Mars’s south pole.'],
      ['What were you built with?', 'A robot arm, a camera, and a laser for studying the sky.'],
      ['Anything fun?', 'Yes! A microphone to record the sounds of Mars.'],
      ['Did you bring friends?', 'Two tiny Deep Space 2 probes that were meant to dig into the ground.'],
      ['What happened?', 'My last message came just before I entered Mars’s air on 3 December 1999.'],
      ['Did you send any science?', 'No. We never called home, and no one knows why.'],
      ['Where are you now?', 'Somewhere near the south pole.'],
    ]),
  }),
  mk({
    id: 'mars-phoenix', name: 'Phoenix', voice: 'sojourner', emoji: '❄️', year: '2007',
    lead: 'I dug up ice!',
    body: 'Phoenix landed on the cold northern plains of Mars in 2008, dug into the ground, and found water ice. The Sun faded and it went quiet in November 2008.',
    speech: 'I landed in the Martian arctic, dug into the ground, and found water ice!',
    fact: 'Phoenix sent its last message on 2 November 2008 as northern summer ended and sunlight faded.',
    orbitLine: 'Phoenix, what did you dig up?',
    interview: chat('Phoenix', [
      ['Phoenix, why did you go to Mars?', 'To study the cold north, and follow the water.'],
      ['What were you built with?', 'A robot arm with a scoop, a camera, and a weather station.'],
      ['Anything else?', 'A tiny chemistry lab that tested soil.'],
      ['What did you find?', 'Water ice just under the soil!'],
      ['Why does that matter?', 'Water is a clue to whether Mars could ever have supported life.'],
      ['Why did you stop?', 'The Sun sank low and my solar power ran out. My last signal was 2 November 2008.'],
      ['Where are you now?', 'Frozen in the Martian north.'],
    ]),
  }),
  mk({
    id: 'mars-insight', name: 'InSight', voice: 'spirit', emoji: '🌍', year: '2018',
    lead: 'I listened for marsquakes!',
    body: 'InSight listened for marsquakes and measured heat from inside Mars. Dust covered its solar panels, and it stopped in December 2022.',
    speech: 'I listened for marsquakes and measured heat from inside Mars!',
    fact: 'InSight stopped talking after 5 December 2022. NASA declared the mission over on 21 December 2022.',
    orbitLine: 'InSight, what did you hear?',
    interview: chat('InSight', [
      ['InSight, why did you go to Mars?', 'To study the inside of Mars: its crust, mantle and core.'],
      ['What were you built with?', 'A very sensitive {{seismometer|quake sensor}}, and a self-hammering heat probe.'],
      ['Anything else?', 'Weather sensors, two cameras, and a radio experiment.'],
      ['What did you learn?', 'I heard many marsquakes. They showed what Mars is like inside.'],
      ['What did the radio do?', 'It tracked Mars’s tiny wobble as it spins.'],
      ['What ended your mission?', 'Dust blocked my solar panels. My last contact was 5 December 2022.'],
      ['Where are you now?', 'Sitting still on a flat plain called Elysium Planitia.'],
    ]),
  }),
  mk({
    id: 'mars-ingenuity', name: 'Ingenuity', voice: 'oppy', emoji: '🚁', year: '2020',
    lead: 'I flew on another planet!',
    body: 'Ingenuity was a helicopter that proved flight is possible in the thin air of Mars. It made 72 flights before a rotor was damaged in January 2024.',
    speech: 'I was the first helicopter on another planet, and I flew 72 times!',
    fact: 'Ingenuity flew 72 times over almost three years and went around 17 km before a damaged rotor blade ended its flights on 18 January 2024.',
    orbitLine: 'Ingenuity, tell us about flying on Mars!',
    interview: chat('Ingenuity', [
      ['Ingenuity, what was your mission?', 'To prove a helicopter can fly in Mars’s thin {{atmosphere|air}}.'],
      ['What are you like?', 'I weigh only 1.8 kg, with two rotors about 1.2 meters wide.'],
      ['How did you get to Mars?', 'I rode on the Perseverance rover!'],
      ['How many flights did you plan?', 'Five. I made 72!'],
      ['What did you do besides test flying?', 'I scouted the ground ahead for Perseverance.'],
      ['What ended your flying?', 'On 18 January 2024, a rotor blade was damaged, so I could not fly again.'],
      ['Where are you now?', 'Grounded on Mars, near Jezero Crater.'],
    ], 'The first helicopter on another world.'),
  }),
];

/* ------------------------------------------------------------------ */
/*  MOON (Rangers, Orbiters, Surveyors, Apollo hardware, more)         */
/* ------------------------------------------------------------------ */
export const MOON_EXTRA = [
  mk({
    id: 'moon-ranger-7', name: 'Ranger 7', emoji: '📷', year: '1964',
    lead: 'My last picture was my best!',
    body: 'Ranger 7 was built to crash into the Moon while photographing it. Its cameras sent 4,308 pictures in its last 17 minutes.',
    speech: 'I took 4,308 pictures on my way down to the Moon!',
    fact: 'Ranger 7 hit the Moon on 31 July 1964. Its final picture was sharp enough to show rocks about half a meter wide.',
    orbitLine: 'Ranger 7, what did you see on the way down?',
    interview: chat('Ranger 7', [
      ['Ranger 7, what was your mission?', 'Fly straight into the Moon, taking close pictures all the way down.'],
      ['What were you built with?', 'Six TV cameras and solar panels.'],
      ['What did you send?', '4,308 pictures in 17 minutes. They were the first close-ups of the Moon by a U.S. spacecraft.'],
      ['Why did that matter?', 'It helped show that some Moon ground is smooth enough for landings.'],
      ['Where are you now?', 'In pieces on a dark plain called Mare Cognitum, where I crashed in 1964.'],
    ]),
  }),
  mk({
    id: 'moon-ranger-8', name: 'Ranger 8', emoji: '📷', year: '1965',
    lead: 'I scouted Apollo’s future landing area!',
    body: 'Ranger 8 photographed the Sea of Tranquility before crashing there on purpose in 1965.',
    speech: 'I photographed the Sea of Tranquility before I crashed on purpose in 1965!',
    fact: 'Ranger 8 sent 7,137 pictures in its last 23 minutes and hit the Moon on 20 February 1965.',
    orbitLine: 'Ranger 8, what did you see?',
    interview: chat('Ranger 8', [
      ['Ranger 8, why did you go to the Moon?', 'To photograph the surface until I crashed into it.'],
      ['What were you built with?', 'Six TV cameras and a radio to send pictures.'],
      ['What did you find?', '7,137 pictures of the Sea of Tranquility.'],
      ['Why does that place matter?', 'Apollo 11 landed near it four years later!'],
      ['How did your mission end?', 'Right on plan, with a crash into the Moon.'],
      ['Where are you now?', 'On the Moon, in the Sea of Tranquility.'],
    ]),
  }),
  mk({
    id: 'moon-ranger-9', name: 'Ranger 9', emoji: '📺', year: '1965',
    lead: 'You watched me crash on TV!',
    body: 'Ranger 9 sent live pictures of the crater Alphonsus, shown on television, until it crashed in 1965.',
    speech: 'I sent live pictures of the crater Alphonsus until I crashed in 1965!',
    fact: 'Ranger 9 sent 5,814 pictures and hit the Moon on 24 March 1965. Many were shown live on TV.',
    orbitLine: 'Ranger 9, you were on TV!',
    interview: chat('Ranger 9', [
      ['Ranger 9, what was your mission?', 'Photograph the crater Alphonsus until I crashed into it.'],
      ['What were you built with?', 'Six TV cameras aimed at the crater.'],
      ['What did you send?', '5,814 sharp pictures.'],
      ['Who saw them?', 'People on TV, live, as I fell!'],
      ['What did we learn?', 'Close views of a crater that helped scientists understand how craters form.'],
      ['Where are you now?', 'Inside Alphonsus crater, where I crashed on 24 March 1965.'],
    ], 'The last of the Rangers.'),
  }),
  mk({
    id: 'moon-lunar-orbiter-1', name: 'Lunar Orbiter 1', emoji: '🛰️', year: '1966',
    lead: 'I scouted landing sites from orbit!',
    body: 'Lunar Orbiter 1 circled the Moon in 1966, photographing possible Apollo landing sites.',
    speech: 'I circled the Moon in 1966 and photographed possible Apollo landing sites!',
    fact: 'Lunar Orbiter 1 took the first picture of Earth from Moon orbit. It was crashed on purpose on 29 October 1966.',
    orbitLine: 'Lunar Orbiter 1, what did you scout?',
    interview: chat('Lunar Orbiter 1', [
      ['Lunar Orbiter 1, what was your mission?', 'Map the Moon in detail and help pick Apollo landing sites.'],
      ['What were you built with?', 'A camera that developed its own film, and sensors for radiation and {{micrometeoroid|space-dust}} hits.'],
      ['What did you discover?', 'Sharp views of possible landing areas.'],
      ['Anything special?', 'I took the first picture of Earth from Moon orbit!'],
      ['Why did you end early?', 'My steering gas was low, and I had to stay out of Lunar Orbiter 2’s way.'],
      ['Where are you now?', 'On the far side of the Moon, where I was crashed on 29 October 1966.'],
    ]),
  }),
  mk({
    id: 'moon-lunar-orbiter-2', name: 'Lunar Orbiter 2', emoji: '🛰️', year: '1966',
    lead: 'I mapped the Moon’s craters.',
    body: 'Lunar Orbiter 2 took detailed photos of craters and landscape for the Apollo program.',
    speech: 'I mapped craters and landscape for Apollo!',
    fact: 'Lunar Orbiter 2 was crashed on purpose on 11 October 1967 after finishing its mission.',
    orbitLine: 'Lunar Orbiter 2, what did you map?',
    interview: chat('Lunar Orbiter 2', [
      ['Lunar Orbiter 2, why did you go to the Moon?', 'To photograph craters and landing sites for Apollo.'],
      ['What were you built with?', 'A film camera, and sensors for radiation and {{micrometeoroid|space-dust}} hits.'],
      ['What did you learn?', 'Detailed shapes of craters and hills.'],
      ['What was your famous picture?', 'A slanted view across the big crater Copernicus!'],
      ['How did your mission end?', 'I was crashed on purpose on 11 October 1967.'],
      ['Where are you now?', 'On the Moon, in my own crater.'],
    ]),
  }),
  mk({
    id: 'moon-lunar-orbiter-3', name: 'Lunar Orbiter 3', emoji: '🛰️', year: '1967',
    lead: 'I found Surveyor 1!',
    body: 'Lunar Orbiter 3 helped confirm safe landing sites, and even spotted the Surveyor 1 lander.',
    speech: 'I helped confirm safe landing sites, and I spotted Surveyor 1!',
    fact: 'Lunar Orbiter 3 was crashed on purpose on 9 October 1967.',
    orbitLine: 'Lunar Orbiter 3, what did you spot?',
    interview: chat('Lunar Orbiter 3', [
      ['Lunar Orbiter 3, what was your mission?', 'Confirm safe landing sites for Surveyor and Apollo.'],
      ['What were you built with?', 'A film camera, and sensors for radiation and {{micrometeoroid|space-dust}} hits.'],
      ['What did you find?', 'Sharp pictures of safe-looking spots.'],
      ['Anything special?', 'I spotted the Surveyor 1 lander on the ground!'],
      ['How did your mission end?', 'I was crashed on purpose on 9 October 1967.'],
      ['Where are you now?', 'On the Moon at my crash site.'],
    ]),
  }),
  mk({
    id: 'moon-lunar-orbiter-4', name: 'Lunar Orbiter 4', emoji: '🛰️', year: '1967',
    lead: 'I mapped the near side!',
    body: 'Lunar Orbiter 4 photographed about 99% of the Moon’s near side. Contact was lost on 17 July 1967.',
    speech: 'I mapped almost the whole near side of the Moon!',
    fact: 'Lunar Orbiter 4 lost contact on 17 July 1967. Its orbit shrank, and it probably hit the Moon by 31 October 1967.',
    orbitLine: 'Lunar Orbiter 4, what did you map?',
    interview: chat('Lunar Orbiter 4', [
      ['Lunar Orbiter 4, what was your mission?', 'Map the side of the Moon that faces Earth.'],
      ['What were you built with?', 'A film camera, and sensors for radiation and {{micrometeoroid|space-dust}} hits.'],
      ['What did you achieve?', 'Pictures of about 99% of the near side.'],
      ['Why was that useful?', 'Scientists could study the whole face of the Moon, and Apollo could pick sites.'],
      ['What happened to your contact?', 'I lost contact on 17 July 1967.'],
      ['Where are you now?', 'Probably on the Moon: my orbit shrank, and I likely crashed by October 1967.'],
    ]),
  }),
  mk({
    id: 'moon-lunar-orbiter-5', name: 'Lunar Orbiter 5', emoji: '🛰️', year: '1967',
    lead: 'The last Orbiter finished the job!',
    body: 'Lunar Orbiter 5 photographed more landing sites and unmapped areas before it was crashed on 31 January 1968.',
    speech: 'I finished the mapping job, and photographed regions nobody had seen!',
    fact: 'Lunar Orbiter 5 ended on 31 January 1968 when it was crashed on purpose.',
    orbitLine: 'Lunar Orbiter 5, the last in the series!',
    interview: chat('Lunar Orbiter 5', [
      ['Lunar Orbiter 5, what was your mission?', 'Take more pictures of Apollo and Surveyor sites, and map places not yet photographed.'],
      ['What were you built with?', 'A film camera, and sensors for radiation and {{micrometeoroid|space-dust}} hits.'],
      ['What did you achieve?', 'Pictures of areas nobody had seen. That finished the series!'],
      ['How did you end?', 'I was crashed on purpose on 31 January 1968.'],
      ['Where are you now?', 'On the Moon at my crash site.'],
    ], 'The whole Moon, mapped.'),
  }),
  mk({
    id: 'moon-surveyor-2', name: 'Surveyor 2', emoji: '💥', year: '1966',
    lead: 'One engine did not start.',
    body: 'Surveyor 2 was meant to land softly, but one of its engines failed on the way and it tumbled and crashed.',
    speech: 'One of my engines failed to start, and I crashed in 1966.',
    fact: 'A small steering engine failed on 21 September 1966, making Surveyor 2 spin. It crashed on the Moon on 22 September 1966.',
    orbitLine: 'Surveyor 2, what went wrong?',
    interview: chat('Surveyor 2', [
      ['Surveyor 2, what was your mission?', 'Land softly on the Moon, take pictures, and study the ground.'],
      ['What were you built with?', 'Three legs, a TV camera, and small steering engines.'],
      ['What went wrong?', 'One steering engine did not start.'],
      ['What did that cause?', 'I began to spin, about once every second.'],
      ['What happened next?', 'Engineers could not fix it. My signal stopped on 22 September 1966.'],
      ['Did you send science?', 'No. But my failure helped engineers fix later Surveyors.'],
      ['Where are you now?', 'On the Moon, in a crater I made when I crashed.'],
    ]),
  }),
  mk({
    id: 'moon-surveyor-3', name: 'Surveyor 3', emoji: '🤖', year: '1967',
    lead: 'Apollo 12 came to visit me!',
    body: 'Surveyor 3 landed in 1967. Two years later, Apollo 12 astronauts landed nearby and brought back some of its parts.',
    speech: 'Apollo 12 astronauts landed near me and took my camera home!',
    fact: 'Apollo 12 landed within 180 m of Surveyor 3 and brought back about 10 kg of its parts, including its TV camera.',
    orbitLine: 'Surveyor 3, what was it like to have visitors?',
    interview: chat('Surveyor 3', [
      ['Surveyor 3, what was your mission?', 'Check whether the Moon’s ground was safe for people.'],
      ['What were you built with?', 'A TV camera and a little scoop arm that dug trenches.'],
      ['What did you learn?', 'The soil was firm enough to walk on.'],
      ['Who visited you?', 'Apollo 12! Pete Conrad and Alan Bean walked up on 20 November 1969.'],
      ['What did they take?', 'About 10 kg of my parts, including my camera. It is now in a museum!'],
      ['Why did they take them?', 'Scientists wanted to see how two years on the Moon changed them.'],
      ['Where are you now?', 'On the Moon. My last contact was May 1967.'],
    ]),
  }),
  mk({
    id: 'moon-surveyor-4', name: 'Surveyor 4', emoji: '❓', year: '1967',
    lead: 'I lost contact just before landing.',
    body: 'Surveyor 4 went silent about two and a half minutes before landing in July 1967.',
    speech: 'I lost contact just before touchdown on the Moon in 1967.',
    fact: 'Surveyor 4’s signal stopped 41 seconds after its braking rocket fired on 17 July 1967. No one knows why.',
    orbitLine: 'Surveyor 4, what happened?',
    interview: chat('Surveyor 4', [
      ['Surveyor 4, what was your mission?', 'Land softly and study the Moon’s ground.'],
      ['What were you built with?', 'Three legs, a TV camera, a soil scoop, and a big {{retrorocket|braking rocket}}.'],
      ['What happened?', 'My signal stopped 41 seconds after the braking rocket fired.'],
      ['How close were you?', 'About two and a half minutes from touchdown!'],
      ['Why did it stop?', 'No one knows. Maybe my rocket failed, or maybe my radio did.'],
      ['Did you send science?', 'No. But engineers learned from my loss.'],
      ['Where are you now?', 'Probably on the Moon. We never heard from me again.'],
    ]),
  }),
  mk({
    id: 'moon-surveyor-5', name: 'Surveyor 5', emoji: '🧪', year: '1967',
    lead: 'I tested the Moon’s chemistry!',
    body: 'Surveyor 5 made the first on-the-spot chemistry test of another world’s ground.',
    speech: 'I made the first chemistry test of another world’s soil!',
    fact: 'Surveyor 5 sent back 19,118 pictures. Its last message came on 17 December 1967.',
    orbitLine: 'Surveyor 5, what is the Moon made of?',
    interview: chat('Surveyor 5', [
      ['Surveyor 5, what was your mission?', 'Land in the Sea of Tranquility and test the soil.'],
      ['What were you built with?', 'A TV camera and a {{spectrometer|rock-chemistry sensor}}.'],
      ['What did you discover?', 'The soil is like {{basalt|basalt}}, a rock that forms from lava.'],
      ['How long did you work?', 'Four Moon days, taking 19,118 pictures.'],
      ['Where are you now?', 'On the Moon, near where Apollo 11 later landed.'],
      ['When did you last call?', 'My final message came on 17 December 1967.'],
    ]),
  }),
  mk({
    id: 'moon-surveyor-6', name: 'Surveyor 6', emoji: '🦘', year: '1967',
    lead: 'I hopped on the Moon!',
    body: 'Surveyor 6 made the first takeoff from the Moon: a hop of a few meters.',
    speech: 'I hopped on the Moon!',
    fact: 'On 17 November 1967, Surveyor 6 lifted off and landed about 2.4 m away, giving two views of the same spot.',
    orbitLine: 'Surveyor 6, you hopped?!',
    interview: chat('Surveyor 6', [
      ['Surveyor 6, what was your mission?', 'Land in a place called Sinus Medii and test the soil.'],
      ['What were you built with?', 'A camera, a {{spectrometer|rock-chemistry sensor}}, and steering rockets.'],
      ['Tell us about your hop!', 'On 17 November 1967 I fired my engines, jumped, and landed a few meters away.'],
      ['Why hop?', 'Two views of the same spot gave 3D pictures of the ground.'],
      ['What did you learn?', 'The soil is {{basalt|basalt}}-like and strong enough for human landings.'],
      ['How many pictures did you send?', '29,952!'],
      ['Where are you now?', 'On the Moon. My last message came on 14 December 1967.'],
    ]),
  }),
  mk({
    id: 'moon-surveyor-7', name: 'Surveyor 7', emoji: '⛰️', year: '1968',
    lead: 'I visited the Moon’s highlands!',
    body: 'Surveyor 7 landed in the rugged highlands near Tycho crater and detected laser beams sent from Earth.',
    speech: 'I explored the highlands near Tycho crater!',
    fact: 'Surveyor 7 sent 21,038 pictures. Highland soil had less iron than the dark plains.',
    orbitLine: 'Surveyor 7, what did you find at Tycho?',
    interview: chat('Surveyor 7', [
      ['Surveyor 7, what was your mission?', 'Study the Moon’s rugged highlands near Tycho crater.'],
      ['What were you built with?', 'A camera, a scoop arm, and a {{spectrometer|rock-chemistry sensor}}.'],
      ['What could your arm do?', 'It dug trenches and moved four rocks.'],
      ['What did you discover?', 'Highland soil has less iron than soil from the dark plains.'],
      ['Anything special?', 'I saw laser beams sent from Earth!'],
      ['Where are you now?', 'Near Tycho. My work ended on 21 February 1968.'],
    ], 'The last Surveyor.'),
  }),
  mk({
    id: 'moon-apollo-12', name: 'Apollo 12', voice: 'apollo', emoji: '🚀', year: '1969',
    lead: 'We landed right next to Surveyor 3!',
    body: 'Apollo 12 landed within about 180 meters of Surveyor 3, left a science station, and brought home 34 kg of samples.',
    speech: 'We landed right next to Surveyor 3!',
    fact: 'Apollo 12 left its lander’s bottom half and a science station called ALSEP on the Moon in November 1969.',
    orbitLine: 'Apollo 12, tell us about your precision landing!',
    interview: chat('Apollo 12', [
      ['Apollo 12, what was your mission?', 'Land very close to Surveyor 3 and set up science instruments.'],
      ['What hardware did you leave?', 'The bottom half of our lunar module, and a science station called ALSEP.'],
      ['What was in the ALSEP?', 'A {{seismometer|quake sensor}}, a {{magnetometer|magnet sensor}}, and detectors for particles from the Sun.'],
      ['What did you bring home?', '34 kg of rocks and soil.'],
      ['Anything else?', 'Parts of Surveyor 3, to see how the Moon changed them.'],
      ['Where are you now?', 'On the Moon. Our parts have been silent since 1969.'],
    ]),
  }),
  mk({
    id: 'moon-apollo-14', name: 'Apollo 14', voice: 'apollo', emoji: '🚀', year: '1971',
    lead: 'We pulled a cart over the Moon!',
    body: 'Apollo 14 landed in the Fra Mauro highlands, set up a science station, and returned over 42 kg of samples.',
    speech: 'We landed in Fra Mauro and brought back 42 kilograms of Moon rock!',
    fact: 'Apollo 14 left its lander’s bottom half and an ALSEP science station on the Moon in 1971.',
    orbitLine: 'Apollo 14, what did you explore?',
    interview: chat('Apollo 14', [
      ['Apollo 14, what was your mission?', 'Explore the Fra Mauro highlands, where Apollo 13 never got to go.'],
      ['What hardware did you leave?', 'The bottom half of our lander, and an ALSEP science station.'],
      ['What was in the ALSEP?', '{{seismometer|Quake sensors}}, a particle detector, and an ion gauge for measuring the Moon’s thin gas.'],
      ['What did you bring home?', '42 kg of rocks and soil.'],
      ['How did you carry your tools?', 'In a hand cart. This mission had no rover!'],
      ['Where are you now?', 'On the Moon. Our parts have been silent since 1971.'],
    ]),
  }),
  mk({
    id: 'moon-lrv-16', name: 'Apollo 16 Rover', voice: 'apollo', emoji: '🚙', year: '1972',
    lead: 'Highlands road trip!',
    body: 'The Apollo 16 Lunar Roving Vehicle drove about 27 km across the Descartes highlands and was left behind.',
    speech: 'I carried Apollo 16 astronauts across the Descartes highlands!',
    fact: 'The Apollo 16 rover drove 26.7 km and was left on the Moon after the mission.',
    orbitLine: 'Apollo 16 Rover, tell us about your drive!',
    interview: chat('Apollo 16 Rover', [
      ['Apollo 16 Rover, what was your job?', 'Carry two astronauts and their tools across the Descartes highlands.'],
      ['What are you made of?', 'A light frame, mesh wheels, and four electric motors.'],
      ['What powered you?', 'Two big batteries.'],
      ['How far did you go?', 'About 26.7 km. Once I went 4.5 km from the lander!'],
      ['What did you help with?', 'We gathered 95 kg of rocks and soil, and set up experiments.'],
      ['Where are you now?', 'Parked on the Moon since April 1972, and no longer working.'],
    ]),
  }),
  mk({
    id: 'moon-apollo-16', name: 'Apollo 16', voice: 'apollo', emoji: '🚀', year: '1972',
    lead: 'We explored the highlands!',
    body: 'Apollo 16 landed in the Descartes Highlands, carried a rover and a science station, and brought home 95.7 kg of samples.',
    speech: 'We explored the lunar highlands and brought back 95 kilograms of samples!',
    fact: 'Apollo 16 left its lander’s bottom half, a rover, and an ALSEP science station on the Moon in April 1972.',
    orbitLine: 'Apollo 16, what did you find in the highlands?',
    interview: chat('Apollo 16', [
      ['Apollo 16, what was your mission?', 'Explore the Moon’s highlands, which are very different from the dark plains.'],
      ['What hardware did you leave?', 'The bottom half of our lander, a rover, and an ALSEP science station.'],
      ['What was in the ALSEP?', '{{seismometer|Quake sensors}}, a {{magnetometer|magnet sensor}}, and a heat probe.'],
      ['What went wrong?', 'The heat probe was damaged while we set it up.'],
      ['What did you bring home?', '95.7 kg of highland rocks and soil.'],
      ['Where are you now?', 'On the Moon at Descartes. Our parts have been silent since 1972.'],
    ]),
  }),
  mk({
    id: 'moon-lrv-17', name: 'Apollo 17 Rover', voice: 'apollo', emoji: '🚙', year: '1972',
    lead: 'The longest Moon drive ever!',
    body: 'The Apollo 17 rover drove about 36 km across the Taurus-Littrow valley, the farthest of the three rovers.',
    speech: 'I drove about 36 kilometers on the Moon, farther than any other rover!',
    fact: 'The Apollo 17 rover drove 35.9 km, the longest of any Apollo rover, and stayed on the Moon.',
    orbitLine: 'Apollo 17 Rover, how far did you go?',
    interview: chat('Apollo 17 Rover', [
      ['Apollo 17 Rover, what was your job?', 'Carry astronauts across the Taurus-Littrow valley.'],
      ['What are you made of?', 'A folding frame that weighed 210 kg, and four mesh wheels.'],
      ['What powered you?', 'Two big batteries.'],
      ['How far did you go?', 'About 36 km, and 7.6 km from the lander at most.'],
      ['What did you help find?', 'Orange soil, and 110 kg of rocks.'],
      ['Where are you now?', 'Parked on the Moon since December 1972.'],
    ]),
  }),
  mk({
    id: 'moon-apollo-17', name: 'Apollo 17', voice: 'apollo', emoji: '🚀', year: '1972',
    lead: 'The last people on the Moon, so far!',
    body: 'Apollo 17 was the final Apollo landing. It brought home the most samples, 110.5 kg, and left a rover and a science station.',
    speech: 'Apollo 17 was the final Moon landing so far, with the most samples ever!',
    fact: 'Apollo 17’s science station measured heat from inside the Moon, the pull of gravity, and the Moon’s thin gas.',
    orbitLine: 'Apollo 17, you were the last!',
    interview: chat('Apollo 17', [
      ['Apollo 17, what was your mission?', 'The last Apollo landing, in the Taurus-Littrow valley.'],
      ['What hardware did you leave?', 'The bottom half of our lander, a rover, and an ALSEP science station.'],
      ['What was in the ALSEP?', 'A heat probe, a gravity meter, and a sensor for the Moon’s thin {{exosphere|air}}.'],
      ['Who was on your crew?', 'Harrison Schmitt, the first scientist to walk on the Moon!'],
      ['What did you bring home?', '110.5 kg of rocks and soil, the most of any mission.'],
      ['Where are you now?', 'On the Moon. Our parts have been silent since 1972.'],
    ]),
  }),
  mk({
    id: 'moon-alsep', name: 'ALSEP', voice: 'apollo', emoji: '🔋', year: '1969–72',
    lead: 'Moon science stations!',
    body: 'ALSEP stations were science kits set up on the Moon by Apollo crews, powered by nuclear batteries. They were switched off in 1977.',
    speech: 'Apollo crews set up science stations on the Moon, and they ran until 1977!',
    fact: 'The ALSEP stations were switched off on 30 September 1977. They are still on the Moon.',
    orbitLine: 'ALSEP, what did you do?',
    interview: chat('ALSEP', [
      ['ALSEP, what are you?', 'The Apollo Lunar Surface Experiments Package, a science kit the crews left on the Moon.'],
      ['Which missions left one?', 'Apollo 12, 14, 15, 16 and 17.'],
      ['What were you built with?', '{{seismometer|Quake sensors}}, {{magnetometer|magnet sensors}}, heat probes, and particle detectors.'],
      ['What powered you?', 'A {{rtg|nuclear battery}} that made power from heat.'],
      ['What did you learn?', 'We felt moonquakes and space rocks hitting the Moon, and measured heat from inside it.'],
      ['How long did you work?', 'For years, until we were switched off in 1977.'],
      ['Where are you now?', 'Sitting on the Moon at five sites, silent.'],
    ], 'Silent now, but not forgotten.'),
  }),
  mk({
    id: 'moon-lunar-prospector', name: 'Lunar Prospector', emoji: '🧲', year: '1998',
    lead: 'I looked for ice at the poles!',
    body: 'Lunar Prospector circled the Moon looking for ice and mapped what the Moon is made of. It ended with a planned crash in 1999.',
    speech: 'I circled the Moon looking for ice at the poles!',
    fact: 'Lunar Prospector found hints of water ice at the Moon’s poles. It was crashed near the south pole on 31 July 1999.',
    orbitLine: 'Lunar Prospector, did you find ice?',
    interview: chat('Lunar Prospector', [
      ['Lunar Prospector, what was your mission?', 'Map what the Moon is made of, and hunt for ice at the poles.'],
      ['What were you built with?', 'Six science instruments, including sensors for rock chemistry and a {{magnetometer|magnet sensor}}.'],
      ['What did you find?', 'Signs of hydrogen at both poles. It could be water ice!'],
      ['Anything else?', 'The Moon seems to have a small core.'],
      ['How did your mission end?', 'On 31 July 1999 I was crashed near the south pole.'],
      ['Why crash?', 'Scientists hoped the crash would kick up water vapor to see.'],
      ['Did it work?', 'No plume was seen. I am still on the Moon.'],
    ]),
  }),
  mk({
    id: 'moon-ladee', name: 'LADEE', emoji: '🌫️', year: '2013',
    lead: 'I tasted the Moon’s thin air!',
    body: 'LADEE circled the Moon to study its very thin atmosphere and dust. It ended with a planned crash in April 2014.',
    speech: 'I studied the thin air and dust around the Moon!',
    fact: 'LADEE hit the Moon on purpose on 18 April 2014.',
    orbitLine: 'LADEE, what did you taste up there?',
    interview: chat('LADEE', [
      ['LADEE, what was your mission?', 'Study the Moon’s super-thin {{exosphere|air}} and its dust.'],
      ['What were you built with?', 'A dust detector, a gas sensor, and an ultraviolet camera.'],
      ['What did you learn?', 'What gases and dust float above the Moon.'],
      ['How did your mission end?', 'On 18 April 2014 I crashed into the Moon on purpose.'],
      ['Where are you now?', 'On the Moon, near the edge of Sundman V crater.'],
    ]),
  }),
];

/* ------------------------------------------------------------------ */
/*  DEEP SPACE (Mariner 5, Snoopy, Galileo, Cassini)                   */
/* ------------------------------------------------------------------ */
export const DEEP_EXTRA = [
  mk({
    id: 'deep-mariner-5', name: 'Mariner 5', voice: 'mariner2', emoji: '🟡', year: '1967',
    lead: 'I woke up a year later!',
    body: 'Mariner 5 flew by Venus in 1967 and studied its air with radio waves. Contact ended in December 1967, but briefly returned in 1968.',
    speech: 'I flew by Venus in 1967, and I woke up again in 1968!',
    fact: 'Mariner 5 lost contact on 4 December 1967 and was briefly heard again on 14 October 1968.',
    orbitLine: 'Mariner 5, tell us about Venus!',
    interview: chat('Mariner 5', [
      ['Mariner 5, what was your mission?', 'Zoom past Venus and study its {{atmosphere|air}}.'],
      ['What were you built with?', 'Solar panels, a dish antenna, and a radio experiment.'],
      ['How does a radio study air?', 'My signal passed through Venus’s air on the way to Earth. The changes showed what the air is like.'],
      ['What did you discover?', 'Venus’s air is very thick and hot.'],
      ['Did you stay in touch?', 'Contact ended on 4 December 1967. I was heard again on 14 October 1968!'],
      ['Where are you now?', 'Going around the Sun.'],
    ]),
  }),
  mk({
    id: 'deep-apollo-10-snoopy', name: 'Apollo 10 Snoopy', voice: 'apollo', emoji: '🐶', year: '1969',
    lead: 'Lost in orbit around the Sun!',
    body: 'Snoopy, Apollo 10’s lunar module, flew within 15 km of the Moon. Its top half was sent into orbit around the Sun in 1969 and never found.',
    speech: 'My top half was sent into orbit around the Sun in 1969, and nobody knows where I am!',
    fact: 'Snoopy’s top half was sent into orbit around the Sun in May 1969. No one has confirmed finding it.',
    orbitLine: 'Snoopy, where did you go?',
    interview: chat('Apollo 10 Snoopy', [
      ['Snoopy, what was your mission?', 'A dress rehearsal for the Moon landing! We flew 15 km above the surface.'],
      ['What are you built like?', 'A lunar module with two parts: a bottom half with legs, and a top half where the crew sits.'],
      ['What did you test?', 'My engine, my landing radar, and my steering. All worked!'],
      ['What did you see?', 'TV pictures of the surface, and the place where Apollo 11 would land.'],
      ['So what did we learn?', 'Everything worked, so Apollo 11 could safely land.'],
      ['What happened to you?', 'My bottom half was dropped. My top half was sent into orbit around the Sun in 1969.'],
      ['Where are you now?', 'Unknown! No one has confirmed finding me.'],
    ], 'Still circling the Sun, or lost.'),
  }),
  mk({
    id: 'deep-galileo', name: 'Galileo', voice: 'voyager', emoji: '🪐', year: '1989',
    lead: 'I orbited Jupiter for eight years!',
    body: 'Galileo circled Jupiter, studied its moons, and dropped a probe into its clouds. In 2003 it was sent into Jupiter on purpose.',
    speech: 'I circled Jupiter, dropped a probe into its clouds, and ended my mission in 2003!',
    fact: 'Galileo launched on 18 October 1989, sent its probe into Jupiter on 7 December 1995, and found hints of an ocean under Europa’s ice.',
    orbitLine: 'Galileo, what did you find at Jupiter?',
    interview: chat('Galileo', [
      ['Galileo, what was your mission?', 'Circle Jupiter and study its moons, its magnetism and its clouds.'],
      ['What were you built with?', 'Two spacecraft in one: an orbiter that weighed 2,380 kg, and a 335 kg probe.'],
      ['What did the probe do?', 'It dived into Jupiter’s clouds and sent data until it was crushed.'],
      ['What did you discover?', 'Hints of a salty ocean under Europa’s ice, and winds faster than 600 km/h.'],
      ['Anything else?', 'The first asteroid with its own tiny moon!'],
      ['How did your mission end?', 'In September 2003 I was steered into Jupiter on purpose, to protect moons like Europa.'],
      ['Where are you now?', 'Inside Jupiter. I no longer exist as a spacecraft.'],
    ]),
  }),
  mk({
    id: 'deep-cassini', name: 'Cassini', voice: 'voyager', emoji: '💍', year: '1997',
    lead: 'I dove into Saturn!',
    body: 'Cassini circled Saturn for 13 years and carried the Huygens probe to Titan. It ended its mission in a planned dive into Saturn in 2017.',
    speech: 'I circled Saturn for thirteen years, then dove into the planet!',
    fact: 'Cassini launched on 15 October 1997 and carried the European Huygens probe to Saturn’s moon Titan.',
    orbitLine: 'Cassini, what did you see at Saturn?',
    interview: chat('Cassini', [
      ['Cassini, what was your mission?', 'Study Saturn, its rings, its moons and its magnetism.'],
      ['What were you built with?', '11 science instruments and a {{rtg|nuclear battery}}.'],
      ['What did you bring along?', 'A small probe called Huygens, to land on {{titan|Titan}}.'],
      ['What did you discover?', 'Water-ice geysers on the moon Enceladus.'],
      ['And on Titan?', 'Lakes on its surface!'],
      ['How did your mission end?', 'In September 2017 I dived into Saturn on purpose, to protect its moons.'],
      ['Where are you now?', 'In Saturn’s clouds. But Huygens still rests on Titan!'],
    ]),
  }),
];
